pipeline {
    agent any
    tools {
        builder 'build'
    }
    environment {
        GO111MODULE = 'on'
    }
    stages {
        stage('Compile') {
            steps {
                sh 'go build'
            }
        }
    }
}

