pipeline {
  agent {
    label 'build'
  }
  environment {
    GO111MODULE = 'on'
  }
  stages {
    stage('Build') {
      parallel {
        stage('Frontend') {
          steps {
            sh """
                cd frontend
                go build
                """
          }
        }
        stage('Backend') {
          steps {
            sh """
                cd backend
                go build
                """
          }
        }
      }
    }
  }
}
