pipeline {
    agent {
          label 'build'
    }
    environment {
        GO111MODULE = 'on'
    }
    stages {
        stage('Compile frontend') {
            steps {
                sh 'go build frontend'
            }
        }
    }
}